version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12xtmy2749plc"
s3_prefix = "lambda"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=724670356997.dkr.ecr.us-west-2.amazonaws.com/lambda"]
